version: "3.8"
services:
  postgeslocal:
    image: postgres
    environment:
      - POSTGRES_PASSWORD="mysecretpassword"
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: model
        target: /var/lib/postgresql/data
  swapi:
    build: .
    environment:
      - PASSD="mysecretpassword"
      - USERD=postgres
      - DBNAMED=postgres
      - HOSTD=postgeslocal
volumes:
  model: